/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Bil_Kompleks.Menu_Kompleks;
import Geometri.Menu_Geometri;
import Kalkulator.Menu_Kalkulator;
import Probstat.Menu_Probstat;
import Sistem_Antrian.Menu_SisTran;

/**
 *
 * @author Microsoft
 */
public class Menu_Utama extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Utama
     */
    public Menu_Utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonBilKompleks = new javax.swing.JButton();
        jButtonMenuProbstat = new javax.swing.JButton();
        jButtonMenuGeometri = new javax.swing.JButton();
        jButtonMenuSistran = new javax.swing.JButton();
        jButtonKalkulator = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(445, 220));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jPanel1.setPreferredSize(new java.awt.Dimension(323, 96));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 26)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kumpulan Rumus & Kalkulator");
        jPanel1.add(jLabel1);

        jLabel2.setText("Silahkan pilih topik kalkulator yang diinginkan:                             ");
        jPanel1.add(jLabel2);

        jButtonBilKompleks.setText("Bil. Kompleks");
        jButtonBilKompleks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBilKompleksActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBilKompleks);

        jButtonMenuProbstat.setText("Probstat");
        jButtonMenuProbstat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuProbstatActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMenuProbstat);

        jButtonMenuGeometri.setText("Geometri");
        jButtonMenuGeometri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuGeometriActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMenuGeometri);

        jButtonMenuSistran.setText("Sistem Antrian");
        jButtonMenuSistran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuSistranActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMenuSistran);

        jButtonKalkulator.setText("Kalkulator");
        jButtonKalkulator.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonKalkulator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKalkulatorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonKalkulator);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 190));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBilKompleksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBilKompleksActionPerformed
        
        Menu_Kompleks mKompleks = new Menu_Kompleks();
        mKompleks.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonBilKompleksActionPerformed

    private void jButtonKalkulatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKalkulatorActionPerformed
        Menu_Kalkulator mKalkulator = new Menu_Kalkulator();
        mKalkulator.setVisible(true);
    }//GEN-LAST:event_jButtonKalkulatorActionPerformed

    private void jButtonMenuSistranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuSistranActionPerformed
        Menu_SisTran mSisTran = new Menu_SisTran();
        mSisTran.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonMenuSistranActionPerformed

    private void jButtonMenuGeometriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuGeometriActionPerformed
        Menu_Geometri mGeometri = new Menu_Geometri();
        mGeometri.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonMenuGeometriActionPerformed

    private void jButtonMenuProbstatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuProbstatActionPerformed
        Menu_Probstat mProbstat = new Menu_Probstat();
        mProbstat.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonMenuProbstatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBilKompleks;
    private javax.swing.JButton jButtonKalkulator;
    private javax.swing.JButton jButtonMenuGeometri;
    private javax.swing.JButton jButtonMenuProbstat;
    private javax.swing.JButton jButtonMenuSistran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
