package Probstat;


import java.text.DecimalFormat;
import java.util.Arrays;

import Main.Menu_Utama;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Menu_Probstat extends javax.swing.JFrame {

    /**
     * Creates new form Statistika
     */
    public Menu_Probstat() {
        initComponents();
    }
    public static double round(double value, int places) {
    if (places < 0) throw new IllegalArgumentException();

    long factor = (long) Math.pow(10, places);
    value = value * factor;
    long tmp = Math.round(value);
    return (double) tmp / factor;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jumlahdata = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        input_data = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        mean = new javax.swing.JLabel();
        hasil_mean = new javax.swing.JTextField();
        median = new javax.swing.JLabel();
        hasil_median = new javax.swing.JTextField();
        modus = new javax.swing.JLabel();
        hasil_modus = new javax.swing.JTextField();
        variansi = new javax.swing.JLabel();
        hasil_variansi = new javax.swing.JTextField();
        standar_deviasi = new javax.swing.JLabel();
        hasil_deviasi = new javax.swing.JTextField();
        q1 = new javax.swing.JLabel();
        hasil_q1 = new javax.swing.JTextField();
        q2 = new javax.swing.JLabel();
        hasil_q2 = new javax.swing.JTextField();
        q3 = new javax.swing.JLabel();
        hasil_q3 = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        jButtonMenuUtama = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(102, 102, 255));

        judul.setBackground(new java.awt.Color(255, 255, 255));
        judul.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setText("PROBABILITAS DAN STATISTIKA");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jumlahdata.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jumlahdata.setForeground(new java.awt.Color(255, 255, 255));
        jumlahdata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jumlahdata.setText("Data");

        input_data.setColumns(20);
        input_data.setRows(5);
        jScrollPane1.setViewportView(input_data);

        mean.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        mean.setText("Rata-rata");

        hasil_mean.setEditable(false);

        median.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        median.setText("Median");

        hasil_median.setEditable(false);

        modus.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        modus.setText("Modus");

        hasil_modus.setEditable(false);

        variansi.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        variansi.setText("Variansi");

        hasil_variansi.setEditable(false);

        standar_deviasi.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        standar_deviasi.setText("Standar Deviasi");

        hasil_deviasi.setEditable(false);

        q1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        q1.setText("Q1");

        hasil_q1.setEditable(false);

        q2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        q2.setText("Q2");

        hasil_q2.setEditable(false);

        q3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        q3.setText("Q3");

        hasil_q3.setEditable(false);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        jButtonMenuUtama.setText("Kembali");
        jButtonMenuUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuUtamaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pisahkan data dengan koma (,)");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mean)
                            .addComponent(median)
                            .addComponent(modus)
                            .addComponent(variansi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hasil_median, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(hasil_mean, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                            .addComponent(hasil_modus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hasil_variansi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(standar_deviasi)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(q1)
                                .addGap(105, 105, 105)
                                .addComponent(q2)))
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hasil_deviasi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(q3)
                                .addGap(84, 84, 84))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judul)
                .addGap(103, 103, 103))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(hasil_q1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(hasil_q2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(hasil_q3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonMenuUtama)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                        .addComponent(jumlahdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jumlahdata, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hitung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(mean)
                        .addGap(19, 19, 19))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(hasil_mean)
                        .addGap(18, 18, 18)))
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(median)
                    .addComponent(hasil_median, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modus)
                    .addComponent(hasil_modus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(variansi)
                    .addComponent(hasil_variansi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(standar_deviasi)
                    .addComponent(hasil_deviasi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1)
                    .addComponent(q2)
                    .addComponent(q3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasil_q1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasil_q2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasil_q3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButtonMenuUtama)
                .addContainerGap())
        );

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // Jumlah data
        String fulldata = input_data.getText();
        String[] dataString = fulldata.split(",");
        Float[] datavalue = Arrays.stream(dataString).map(Float::valueOf).toArray(Float[]::new);
        Arrays.sort(datavalue);
        float total=0;
        for (int i = 0; i < datavalue.length; i++){
            total += datavalue[i];
        }
        // Rata - Rata
        float mean = total/datavalue.length;
        hasil_mean.setText(Float.toString(mean));
        // Modus
        Float[] modus = {Float.valueOf(0), Float.valueOf(0)};
        for (float a:datavalue){
            float count = 0;
            for (int i = 0; i < datavalue.length; i++){
                if (a == datavalue[i]){
                    count++;                    
                }    
            }
            if (count>modus[0]){
                modus[0]=count;
                modus[1]=a;
            }
        }
        hasil_modus.setText(Float.toString(modus[1]));
        // Median
        int median = datavalue.length%2;
        float m;
        if (median == 1){
            m = datavalue[datavalue.length/2];
            }else{
            m = (datavalue[datavalue.length/2-1] + datavalue[datavalue.length/2]);
            m = m/2;
            }
        hasil_median.setText(Float.toString(m));
        // Quartil
        float q1 = (float)(datavalue.length + 1)/4;
        float q2 = (float)(2*(datavalue.length + 1))/4;
        float q3 = (float)(3*(datavalue.length + 1))/4;
        int q1b = Math.round(q1);
        int q2b = Math.round(q2);
        int q3b = Math.round(q3);
        float nq1 = datavalue[q1b-1] + ((datavalue[q1b]-datavalue[q1b-1]) * (q1-q1b));
        float nq2 = datavalue[q2b-1] + ((datavalue[q2b]-datavalue[q2b-1]) * (q2-q2b));
        float nq3 = datavalue[q3b-1] + ((datavalue[q3b]-datavalue[q3b-1]) * (q3-q3b));
        hasil_q1.setText(Float.toString(nq1));
        hasil_q2.setText(Float.toString(nq2));
        hasil_q3.setText(Float.toString(nq3));
        // Variansi
        double sigma =0;
        for (int i = 0; i < datavalue.length; i++){
            sigma = sigma + Math.pow(datavalue[i]- mean,2); 
        
        }
        double nilai_variansi = sigma/(datavalue.length-1);
        hasil_variansi.setText(Double.toString(round(nilai_variansi,3)));
        //Standar Deviasi
        double deviasi = 0;
        deviasi = Math.sqrt(((nilai_variansi)));
        
        hasil_deviasi.setText(Double.toString(round(deviasi,3)));
    }//GEN-LAST:event_hitungActionPerformed

    private void jButtonMenuUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuUtamaActionPerformed
        Menu_Utama mUtama = new Menu_Utama();
        mUtama.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonMenuUtamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Probstat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Probstat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Probstat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Probstat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Probstat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JTextField hasil_deviasi;
    private javax.swing.JTextField hasil_mean;
    private javax.swing.JTextField hasil_median;
    private javax.swing.JTextField hasil_modus;
    private javax.swing.JTextField hasil_q1;
    private javax.swing.JTextField hasil_q2;
    private javax.swing.JTextField hasil_q3;
    private javax.swing.JTextField hasil_variansi;
    private javax.swing.JButton hitung;
    private javax.swing.JTextArea input_data;
    private javax.swing.JButton jButtonMenuUtama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel jumlahdata;
    private javax.swing.JLabel mean;
    private javax.swing.JLabel median;
    private javax.swing.JLabel modus;
    private javax.swing.JLabel q1;
    private javax.swing.JLabel q2;
    private javax.swing.JLabel q3;
    private javax.swing.JLabel standar_deviasi;
    private javax.swing.JLabel variansi;
    // End of variables declaration//GEN-END:variables

    private double getInfoValueNumeric() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
